spring.application.name=createmanagesubmit
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=true
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# Configuración SMTP (REVISADA)
spring.mail.host=${SP_MAIL_HOST}
spring.mail.port=${SP_MAIL_PORT}
spring.mail.username=${SP_MAIL_USERNAME}
spring.mail.password=${SP_MAIL_PASSWORD}
spring.mail.protocol=smtps

# Propiedades SMTP (Configuración Simplificada)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false  
spring.mail.properties.mail.smtp.socketFactory.port=${SP_MAIL_PORT}
spring.mail.properties.mail.smtp.ssl.trust=${SP_MAIL_HOST}
server.tomcat.additional-tld-skip-patterns=java_websocket.jar,unoloader.jar
spring.jpa.open-in-view=true
spring.mail.properties.mail.debug=true


# Quartz
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_

# Server
server.address=0.0.0.0
server.port=8080
spring.mvc.hiddenmethod.filter.enabled=true

