spring.application.name=createmanagesubmit
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=true
spring.datasource.url=jdbc:mariadb://localhost:3306/appevolution
spring.datasource.username=root
spring.datasource.password=fqZeqZOUZskDInS
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# Configuración SMTP (REVISADA)
spring.mail.host=mail.e-volution.cl
spring.mail.port=465
spring.mail.username=diplomas@e-volution.cl
spring.mail.password=bUS39WvrTye
spring.mail.protocol=smtps

# Propiedades SMTP (Configuración Simplificada)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false  
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.ssl.trust=mail.e-volution.cl
server.tomcat.additional-tld-skip-patterns=java_websocket.jar,unoloader.jar
spring.jpa.open-in-view=true
spring.mail.properties.mail.debug=true


# Quartz
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_